pullPolicy: "IfNotPresent"
ingressIP: "" # defined during helm install
#tls:
#  - credentialsSecretName: voyager-ovh-example-com
#    provider: ovh
#    refName: tls-example-com # deprecated
#    hosts:
#      - one.example.com
#      - two.example.com

images:
  fhirviz:
    repository: "taktik/ehealth-fhirviz"
    tag: ""
    replicaCount: 1
    javaOpts: "-XX:MaxRAMPercentage=70"
    memoryRequest: "4Gi"
    cpuRequest: 5m
    cpuLimit: 2
    debug: true
    env: {}
